# Generated by Django 6.0.1 on 2026-04-15 12:47

import core.models.environment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_s3_backup_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="path",
            field=models.CharField(
                help_text="Directory name within the environments folder",
                max_length=255,
                unique=True,
                validators=[core.models.environment.validate_environment_path],
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="timeout_seconds",
            field=models.PositiveIntegerField(
                default=3600,
                help_text="Maximum execution time in seconds (default: 1 hour, max: 24 hours)",
            ),
        ),
        migrations.AlterField(
            model_name="scriptschedule",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for scheduled runs (e.g., 'America/New_York')",
                max_length=50,
            ),
        ),
    ]
